### ISSUE TITLE
the meaning of 'package_images_lmdb.py'

### ISSUE THREAD

**Issue by redorangeyellowy** [zc-alexfan/digit-interacting#6]
Thank you for your excellent research.

I wonder the meaning of the code `package_images_lmdb.py` in `scripts`.

1. At line 12, why `fnames` is redefined as `fnames[:1000]`?
2. At line 14, why `5130240` is multiplied to `len(fnames)`?

I'll be waiting for the reply. Thank you.

**Comment by zc-alexfan** [comment]
Line 12 just to subsample the number of images so that you can test out whether lmdb work properly. If you want to create for the entire dataset, you can remove that line.

Line 14, lmdb needs to specify the number of bytes in total to store images I think. However, I have forgotten because the code just work after I pick this "magic number". Maybe try to play around with this number if you encounter any problem.
